version: '3.7'
services:
        rproxy:
                image: nginx:alpine
                container_name: rproxy
                ports:
                        - 443:443
                        - 80:80
                volumes:
                        - /var/run/docker.sock:/tmp/docker.sock:ro
                        - ./conf/nginx.conf:/etc/nginx/nginx.conf
                        - ./sites-enabled:/etc/nginx/sites-enabled
                        - ./sites-available:/etc/nginx/sites-available
                        - ./logs:/var/log/nginx
                networks:
                        - frontend-network
                        - backend-network

networks:
  frontend-network:
          external: true
  backend-network:
          external: true
